import { InstitutionsService } from "./institutions.service";
import { InstitutionInviteService } from "./institution-invite.service";
import { InstitutionDomainService } from "./institution-domain.service";
import { ApprovalService } from "./approval.service";
import { SSOService } from "./sso.service";
import { BulkService } from "../bulk/bulk.service";
import { CreateInstitutionDto, UpdateInstitutionDto, CreateInviteDto, AddDomainDto, ProcessApprovalDto } from "./dto/institution.dto";
export declare class InstitutionsController {
    private readonly institutionsService;
    private readonly inviteService;
    private readonly domainService;
    private readonly approvalService;
    private readonly ssoService;
    private readonly bulkService;
    constructor(institutionsService: InstitutionsService, inviteService: InstitutionInviteService, domainService: InstitutionDomainService, approvalService: ApprovalService, ssoService: SSOService, bulkService: BulkService);
    create(createInstitutionDto: CreateInstitutionDto): Promise<{
        id: any;
        name: any;
        type: any;
        kind: any;
        city: any;
        state: any;
        country: any;
        maxMembers: any;
        requiresApproval: any;
        slug: any;
        ssoEnabled: any;
        createdAt: any;
        updatedAt: any;
        memberCount: any;
        activeInvites: any;
        pendingApprovals: any;
        domains: any;
    }>;
    findAll(): Promise<{
        id: any;
        name: any;
        type: any;
        kind: any;
        city: any;
        state: any;
        country: any;
        maxMembers: any;
        requiresApproval: any;
        slug: any;
        ssoEnabled: any;
        createdAt: any;
        updatedAt: any;
        memberCount: any;
        activeInvites: any;
        pendingApprovals: any;
        domains: any;
    }[]>;
    getMyInstitution(req: any): Promise<{
        id: any;
        name: any;
        type: any;
        kind: any;
        city: any;
        state: any;
        country: any;
        maxMembers: any;
        requiresApproval: any;
        slug: any;
        ssoEnabled: any;
        createdAt: any;
        updatedAt: any;
        memberCount: any;
        activeInvites: any;
        pendingApprovals: any;
        domains: any;
    }>;
    findOne(id: string): Promise<{
        id: any;
        name: any;
        type: any;
        kind: any;
        city: any;
        state: any;
        country: any;
        maxMembers: any;
        requiresApproval: any;
        slug: any;
        ssoEnabled: any;
        createdAt: any;
        updatedAt: any;
        memberCount: any;
        activeInvites: any;
        pendingApprovals: any;
        domains: any;
    }>;
    update(id: string, updateInstitutionDto: UpdateInstitutionDto): Promise<{
        id: any;
        name: any;
        type: any;
        kind: any;
        city: any;
        state: any;
        country: any;
        maxMembers: any;
        requiresApproval: any;
        slug: any;
        ssoEnabled: any;
        createdAt: any;
        updatedAt: any;
        memberCount: any;
        activeInvites: any;
        pendingApprovals: any;
        domains: any;
    }>;
    remove(id: string): Promise<void>;
    createInvite(institutionId: string, createInviteDto: CreateInviteDto, req: any): Promise<{
        id: string;
        email: string;
        role: import(".prisma/client").$Enums.InstitutionRole;
        expiresAt: Date;
        inviteUrl: string;
    }>;
    getInvites(institutionId: string): Promise<import("./domain/institution-invite.entity").InstitutionInvite[]>;
    cancelInvite(inviteId: string, req: any): Promise<{
        message: string;
    }>;
    bulkInvite(id: string, file: Express.Multer.File): Promise<{
        success: number;
        failed: number;
        errors: string[];
    }>;
    exportMembers(id: string): Promise<{
        csv: string;
    }>;
    addDomain(institutionId: string, addDomainDto: AddDomainDto, req: any): Promise<import("./domain/domains.repository.interface").InstitutionDomain>;
    getDomains(institutionId: string): Promise<import("./domain/domains.repository.interface").InstitutionDomain[]>;
    removeDomain(domainId: string, req: any): Promise<{
        message: string;
    }>;
    getPendingApprovals(institutionId: string): Promise<import("./domain/pending-approval.entity").PendingApproval[]>;
    processApproval(approvalId: string, processApprovalDto: ProcessApprovalDto, req: any): Promise<{
        id: string;
        created_at: Date;
        updated_at: Date;
        name: string;
        email: string;
        bio: string | null;
        address: string | null;
        sex: string | null;
        birthday: Date | null;
        age: number | null;
        password_hash: string | null;
        system_role: import(".prisma/client").$Enums.SystemRole | null;
        last_context_role: import(".prisma/client").$Enums.ContextRole;
        last_institution_id: string | null;
        oauth_provider: string | null;
        oauth_id: string | null;
        oauth_picture: string | null;
        schooling_level: string | null;
        preferred_languages: import("@prisma/client/runtime/library").JsonValue;
        last_login_at: Date | null;
        status: string;
        avatar_url: string | null;
        settings: import("@prisma/client/runtime/library").JsonValue | null;
        sso_provider: string | null;
        sso_subject: string | null;
        password_reset_token: string | null;
        password_reset_expires: Date | null;
    } | {
        message: string;
    }>;
    createSSOConfig(institutionId: string, dto: any, req: any): Promise<{
        provider: import(".prisma/client").$Enums.SSOProvider;
        id: string;
        created_at: Date;
        updated_at: Date;
        institution_id: string;
        enabled: boolean;
        client_id: string | null;
        entity_id: string | null;
        sso_url: string | null;
        certificate: string | null;
        client_secret: string | null;
        auth_url: string | null;
        token_url: string | null;
        user_info_url: string | null;
        email_attribute: string | null;
        name_attribute: string | null;
        role_attribute: string | null;
        role_mapping: import("@prisma/client/runtime/library").JsonValue | null;
    }>;
    getSSOConfig(institutionId: string): Promise<{
        clientSecret: string;
        certificate: string;
        institutions: {
            id: string;
            name: string;
        };
        provider: import(".prisma/client").$Enums.SSOProvider;
        id: string;
        created_at: Date;
        updated_at: Date;
        institution_id: string;
        enabled: boolean;
        client_id: string | null;
        entity_id: string | null;
        sso_url: string | null;
        client_secret: string | null;
        auth_url: string | null;
        token_url: string | null;
        user_info_url: string | null;
        email_attribute: string | null;
        name_attribute: string | null;
        role_attribute: string | null;
        role_mapping: import("@prisma/client/runtime/library").JsonValue | null;
    }>;
    updateSSOConfig(institutionId: string, dto: any, req: any): Promise<{
        provider: import(".prisma/client").$Enums.SSOProvider;
        id: string;
        created_at: Date;
        updated_at: Date;
        institution_id: string;
        enabled: boolean;
        client_id: string | null;
        entity_id: string | null;
        sso_url: string | null;
        certificate: string | null;
        client_secret: string | null;
        auth_url: string | null;
        token_url: string | null;
        user_info_url: string | null;
        email_attribute: string | null;
        name_attribute: string | null;
        role_attribute: string | null;
        role_mapping: import("@prisma/client/runtime/library").JsonValue | null;
    }>;
    deleteSSOConfig(institutionId: string, req: any): Promise<{
        message: string;
    }>;
    testSSOConfig(institutionId: string): Promise<{
        success: boolean;
        message: string;
    }>;
}
