import { SuppressReason, SuppressionContext, computeSuppressReasons } from './decision.suppress';

describe('Decision Suppression Logic', () => {
  describe('computeSuppressReasons', () => {
    it.each([
      {
        name: 'POLICY_DISABLED when transfer disabled',
        ctx: {
          phase: 'POST' as const,
          explicitAsk: false,
          lowFlow: false,
          cooldownActive: false,
          policyTransferEnabled: false,
          llmEnabled: true,
          budgetExceeded: false,
          rateLimited: false,
          missingInputs: false,
          safetyGuardTriggered: false,
          degradedCapability: false,
        },
        expectedReasons: [SuppressReason.POLICY_DISABLED],
      },
      {
        name: 'BUDGET_EXCEEDED when budget exceeded',
        ctx: {
          phase: 'POST' as const,
          explicitAsk: false,
          lowFlow: false,
          cooldownActive: false,
          policyTransferEnabled: true,
          llmEnabled: true,
          budgetExceeded: true,
          rateLimited: false,
          missingInputs: false,
          safetyGuardTriggered: false,
          degradedCapability: false,
        },
        expectedReasons: [SuppressReason.BUDGET_EXCEEDED],
      },
      {
        name: 'PHASE_DURING_INVISIBLE when DURING phase without explicit ask',
        ctx: {
          phase: 'DURING' as const,
          explicitAsk: false,
          lowFlow: false,
          cooldownActive: false,
          policyTransferEnabled: true,
          llmEnabled: true,
          budgetExceeded: false,
          rateLimited: false,
          missingInputs: false,
          safetyGuardTriggered: false,
          degradedCapability: false,
        },
        expectedReasons: [SuppressReason.PHASE_DURING_INVISIBLE],
      },
      {
        name: 'LOW_FLOW_SILENCE when low flow',
        ctx: {
          phase: 'POST' as const,
          explicitAsk: false,
          lowFlow: true,
          cooldownActive: false,
          policyTransferEnabled: true,
          llmEnabled: true,
          budgetExceeded: false,
          rateLimited: false,
          missingInputs: false,
          safetyGuardTriggered: false,
          degradedCapability: false,
        },
        expectedReasons: [SuppressReason.LOW_FLOW_SILENCE],
      },
      {
        name: 'COOLDOWN_ACTIVE when cooldown active',
        ctx: {
          phase: 'POST' as const,
          explicitAsk: false,
          lowFlow: false,
          cooldownActive: true,
          policyTransferEnabled: true,
          llmEnabled: true,
          budgetExceeded: false,
          rateLimited: false,
          missingInputs: false,
          safetyGuardTriggered: false,
          degradedCapability: false,
        },
        expectedReasons: [SuppressReason.COOLDOWN_ACTIVE],
      },
      {
        name: 'RATE_LIMITED when rate limited',
        ctx: {
          phase: 'POST' as const,
          explicitAsk: false,
          lowFlow: false,
          cooldownActive: false,
          policyTransferEnabled: true,
          llmEnabled: true,
          budgetExceeded: false,
          rateLimited: true,
          missingInputs: false,
          safetyGuardTriggered: false,
          degradedCapability: false,
        },
        expectedReasons: [SuppressReason.RATE_LIMITED],
      },
      {
        name: 'SAFETY_GUARD when safety guard triggered',
        ctx: {
          phase: 'POST' as const,
          explicitAsk: false,
          lowFlow: false,
          cooldownActive: false,
          policyTransferEnabled: true,
          llmEnabled: true,
          budgetExceeded: false,
          rateLimited: false,
          missingInputs: false,
          safetyGuardTriggered: true,
          degradedCapability: false,
        },
        expectedReasons: [SuppressReason.SAFETY_GUARD],
      },
      {
        name: 'MISSING_INPUTS when inputs missing',
        ctx: {
          phase: 'POST' as const,
          explicitAsk: false,
          lowFlow: false,
          cooldownActive: false,
          policyTransferEnabled: true,
          llmEnabled: true,
          budgetExceeded: false,
          rateLimited: false,
          missingInputs: true,
          safetyGuardTriggered: false,
          degradedCapability: false,
        },
        expectedReasons: [SuppressReason.MISSING_INPUTS],
      },
      {
        name: 'DEGRADED_CAPABILITY when degraded',
        ctx: {
          phase: 'POST' as const,
          explicitAsk: false,
          lowFlow: false,
          cooldownActive: false,
          policyTransferEnabled: true,
          llmEnabled: true,
          budgetExceeded: false,
          rateLimited: false,
          missingInputs: false,
          safetyGuardTriggered: false,
          degradedCapability: true,
        },
        expectedReasons: [SuppressReason.DEGRADED_CAPABILITY],
      },
      {
        name: 'Multiple reasons in priority order',
        ctx: {
          phase: 'DURING' as const,
          explicitAsk: false,
          lowFlow: true,
          cooldownActive: false,
          policyTransferEnabled: false,
          llmEnabled: true,
          budgetExceeded: true,
          rateLimited: false,
          missingInputs: false,
          safetyGuardTriggered: false,
          degradedCapability: false,
        },
        expectedReasons: [
          SuppressReason.POLICY_DISABLED,
          SuppressReason.PHASE_DURING_INVISIBLE,
          SuppressReason.LOW_FLOW_SILENCE,
          SuppressReason.BUDGET_EXCEEDED,
        ],
      },
    ])('should return $name', ({ ctx, expectedReasons }) => {
      const reasons = computeSuppressReasons(ctx);
      expect(reasons).toEqual(expectedReasons);
    });
  });
});
